version: "3.6"

services:
  nginx:
    image: nginx:1.10.3
    hostname: ${COMPOSE_PROJECT_NAME}_nginx
    container_name: ${COMPOSE_PROJECT_NAME}_nginx
    restart: unless-stopped
    depends_on:
      - frontend
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ../../static:/app/static:cached
    ports:
      - 8${PROJECT_ID}:80

  frontend:
    hostname: ${COMPOSE_PROJECT_NAME}_frontend
    container_name: ${COMPOSE_PROJECT_NAME}_frontend
    build:
      args:
        UID: "$UID"
      context: ./frontend
    expose:
      - "3000"
    restart: unless-stopped
    volumes:
      - ../../frontend:/app:cached
      - ${HOME}/.npm:${HOME}/.npm
      - ${HOME}/.ssh:${HOME}/.ssh
